/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as WorkspaceRouteRouteImport } from './routes/workspace/route'
import { Route as GuestRouteRouteImport } from './routes/guest/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as GuestIndexRouteImport } from './routes/guest/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WorkspaceWorkspaceIdRouteImport } from './routes/workspace/$workspaceId'
import { Route as GuestProjectIdRouteImport } from './routes/guest/$projectId'
import { Route as AdminWorkspacesRouteImport } from './routes/admin/workspaces'
import { Route as AdminDevToolsRouteImport } from './routes/admin/dev-tools'
import { Route as WorkspaceWorkspaceIdSettingsRouteImport } from './routes/workspace/$workspaceId.settings'
import { Route as WorkspaceWorkspaceIdProjectsRouteImport } from './routes/workspace/$workspaceId.projects'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const WorkspaceWorkspaceIdRoute = WorkspaceWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const GuestProjectIdRoute = GuestProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AdminWorkspacesRoute = AdminWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDevToolsRoute = AdminDevToolsRouteImport.update({
  id: '/dev-tools',
  path: '/dev-tools',
  getParentRoute: () => AdminRouteRoute,
} as any)
const WorkspaceWorkspaceIdSettingsRoute =
  WorkspaceWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)
const WorkspaceWorkspaceIdProjectsRoute =
  WorkspaceWorkspaceIdProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => WorkspaceWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/guest': typeof GuestRouteRouteWithChildren
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/admin/dev-tools': typeof AdminDevToolsRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/guest/$projectId': typeof GuestProjectIdRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/guest/': typeof GuestIndexRoute
  '/login': typeof LoginIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/$workspaceId/projects': typeof WorkspaceWorkspaceIdProjectsRoute
  '/workspace/$workspaceId/settings': typeof WorkspaceWorkspaceIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin/dev-tools': typeof AdminDevToolsRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/guest/$projectId': typeof GuestProjectIdRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/guest': typeof GuestIndexRoute
  '/login': typeof LoginIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/workspace/$workspaceId/projects': typeof WorkspaceWorkspaceIdProjectsRoute
  '/workspace/$workspaceId/settings': typeof WorkspaceWorkspaceIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/guest': typeof GuestRouteRouteWithChildren
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/admin/dev-tools': typeof AdminDevToolsRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/guest/$projectId': typeof GuestProjectIdRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/guest/': typeof GuestIndexRoute
  '/login/': typeof LoginIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/$workspaceId/projects': typeof WorkspaceWorkspaceIdProjectsRoute
  '/workspace/$workspaceId/settings': typeof WorkspaceWorkspaceIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/guest'
    | '/workspace'
    | '/$'
    | '/admin/dev-tools'
    | '/admin/workspaces'
    | '/guest/$projectId'
    | '/workspace/$workspaceId'
    | '/admin/'
    | '/guest/'
    | '/login'
    | '/workspace/'
    | '/workspace/$workspaceId/projects'
    | '/workspace/$workspaceId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin/dev-tools'
    | '/admin/workspaces'
    | '/guest/$projectId'
    | '/workspace/$workspaceId'
    | '/admin'
    | '/guest'
    | '/login'
    | '/workspace'
    | '/workspace/$workspaceId/projects'
    | '/workspace/$workspaceId/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/guest'
    | '/workspace'
    | '/$'
    | '/admin/dev-tools'
    | '/admin/workspaces'
    | '/guest/$projectId'
    | '/workspace/$workspaceId'
    | '/admin/'
    | '/guest/'
    | '/login/'
    | '/workspace/'
    | '/workspace/$workspaceId/projects'
    | '/workspace/$workspaceId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest/': {
      id: '/guest/'
      path: '/'
      fullPath: '/guest/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/workspace/$workspaceId': {
      id: '/workspace/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/guest/$projectId': {
      id: '/guest/$projectId'
      path: '/$projectId'
      fullPath: '/guest/$projectId'
      preLoaderRoute: typeof GuestProjectIdRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/admin/workspaces': {
      id: '/admin/workspaces'
      path: '/workspaces'
      fullPath: '/admin/workspaces'
      preLoaderRoute: typeof AdminWorkspacesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dev-tools': {
      id: '/admin/dev-tools'
      path: '/dev-tools'
      fullPath: '/admin/dev-tools'
      preLoaderRoute: typeof AdminDevToolsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/workspace/$workspaceId/settings': {
      id: '/workspace/$workspaceId/settings'
      path: '/settings'
      fullPath: '/workspace/$workspaceId/settings'
      preLoaderRoute: typeof WorkspaceWorkspaceIdSettingsRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
    '/workspace/$workspaceId/projects': {
      id: '/workspace/$workspaceId/projects'
      path: '/projects'
      fullPath: '/workspace/$workspaceId/projects'
      preLoaderRoute: typeof WorkspaceWorkspaceIdProjectsRouteImport
      parentRoute: typeof WorkspaceWorkspaceIdRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDevToolsRoute: typeof AdminDevToolsRoute
  AdminWorkspacesRoute: typeof AdminWorkspacesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDevToolsRoute: AdminDevToolsRoute,
  AdminWorkspacesRoute: AdminWorkspacesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestProjectIdRoute: typeof GuestProjectIdRoute
  GuestIndexRoute: typeof GuestIndexRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestProjectIdRoute: GuestProjectIdRoute,
  GuestIndexRoute: GuestIndexRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

interface WorkspaceWorkspaceIdRouteChildren {
  WorkspaceWorkspaceIdProjectsRoute: typeof WorkspaceWorkspaceIdProjectsRoute
  WorkspaceWorkspaceIdSettingsRoute: typeof WorkspaceWorkspaceIdSettingsRoute
}

const WorkspaceWorkspaceIdRouteChildren: WorkspaceWorkspaceIdRouteChildren = {
  WorkspaceWorkspaceIdProjectsRoute: WorkspaceWorkspaceIdProjectsRoute,
  WorkspaceWorkspaceIdSettingsRoute: WorkspaceWorkspaceIdSettingsRoute,
}

const WorkspaceWorkspaceIdRouteWithChildren =
  WorkspaceWorkspaceIdRoute._addFileChildren(WorkspaceWorkspaceIdRouteChildren)

interface WorkspaceRouteRouteChildren {
  WorkspaceWorkspaceIdRoute: typeof WorkspaceWorkspaceIdRouteWithChildren
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceWorkspaceIdRoute: WorkspaceWorkspaceIdRouteWithChildren,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
