/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as LogoutRouteImport } from './app/logout'
import { Route as LoginRouteImport } from './app/login'
import { Route as SplatRouteImport } from './app/$'
import { Route as WorkspaceRouteRouteImport } from './app/workspace/route'
import { Route as GuestRouteRouteImport } from './app/guest/route'
import { Route as AdminRouteRouteImport } from './app/admin/route'
import { Route as IndexRouteImport } from './app/index'
import { Route as WorkspaceIndexRouteImport } from './app/workspace/index'
import { Route as GuestIndexRouteImport } from './app/guest/index'
import { Route as AdminIndexRouteImport } from './app/admin/index'
import { Route as WorkspaceWorkspaceSlugRouteImport } from './app/workspace/$workspaceSlug'
import { Route as GuestProjectIdRouteImport } from './app/guest/$projectId'
import { Route as AdminDevToolsRouteRouteImport } from './app/admin/dev-tools/route'
import { Route as WorkspaceWorkspaceSlugIndexRouteImport } from './app/workspace/$workspaceSlug.index'
import { Route as AdminWorkspacesIndexRouteImport } from './app/admin/workspaces/index'
import { Route as WorkspaceWorkspaceSlugSettingsRouteImport } from './app/workspace/$workspaceSlug.settings'
import { Route as WorkspaceWorkspaceSlugProjectsRouteImport } from './app/workspace/$workspaceSlug.projects'
import { Route as AdminWorkspacesCreateRouteImport } from './app/admin/workspaces/create'
import { Route as AdminDevToolsPreviewShellRouteImport } from './app/admin/dev-tools/preview-shell'
import { Route as AdminDevToolsCameraRouteImport } from './app/admin/dev-tools/camera'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const WorkspaceWorkspaceSlugRoute = WorkspaceWorkspaceSlugRouteImport.update({
  id: '/$workspaceSlug',
  path: '/$workspaceSlug',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const GuestProjectIdRoute = GuestProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AdminDevToolsRouteRoute = AdminDevToolsRouteRouteImport.update({
  id: '/dev-tools',
  path: '/dev-tools',
  getParentRoute: () => AdminRouteRoute,
} as any)
const WorkspaceWorkspaceSlugIndexRoute =
  WorkspaceWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkspaceSlugRoute,
  } as any)
const AdminWorkspacesIndexRoute = AdminWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const WorkspaceWorkspaceSlugSettingsRoute =
  WorkspaceWorkspaceSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WorkspaceWorkspaceSlugRoute,
  } as any)
const WorkspaceWorkspaceSlugProjectsRoute =
  WorkspaceWorkspaceSlugProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => WorkspaceWorkspaceSlugRoute,
  } as any)
const AdminWorkspacesCreateRoute = AdminWorkspacesCreateRouteImport.update({
  id: '/workspaces/create',
  path: '/workspaces/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDevToolsPreviewShellRoute =
  AdminDevToolsPreviewShellRouteImport.update({
    id: '/preview-shell',
    path: '/preview-shell',
    getParentRoute: () => AdminDevToolsRouteRoute,
  } as any)
const AdminDevToolsCameraRoute = AdminDevToolsCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => AdminDevToolsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/guest': typeof GuestRouteRouteWithChildren
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/admin/dev-tools': typeof AdminDevToolsRouteRouteWithChildren
  '/guest/$projectId': typeof GuestProjectIdRoute
  '/workspace/$workspaceSlug': typeof WorkspaceWorkspaceSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/guest/': typeof GuestIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/admin/dev-tools/camera': typeof AdminDevToolsCameraRoute
  '/admin/dev-tools/preview-shell': typeof AdminDevToolsPreviewShellRoute
  '/admin/workspaces/create': typeof AdminWorkspacesCreateRoute
  '/workspace/$workspaceSlug/projects': typeof WorkspaceWorkspaceSlugProjectsRoute
  '/workspace/$workspaceSlug/settings': typeof WorkspaceWorkspaceSlugSettingsRoute
  '/admin/workspaces': typeof AdminWorkspacesIndexRoute
  '/workspace/$workspaceSlug/': typeof WorkspaceWorkspaceSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/admin/dev-tools': typeof AdminDevToolsRouteRouteWithChildren
  '/guest/$projectId': typeof GuestProjectIdRoute
  '/admin': typeof AdminIndexRoute
  '/guest': typeof GuestIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/admin/dev-tools/camera': typeof AdminDevToolsCameraRoute
  '/admin/dev-tools/preview-shell': typeof AdminDevToolsPreviewShellRoute
  '/admin/workspaces/create': typeof AdminWorkspacesCreateRoute
  '/workspace/$workspaceSlug/projects': typeof WorkspaceWorkspaceSlugProjectsRoute
  '/workspace/$workspaceSlug/settings': typeof WorkspaceWorkspaceSlugSettingsRoute
  '/admin/workspaces': typeof AdminWorkspacesIndexRoute
  '/workspace/$workspaceSlug': typeof WorkspaceWorkspaceSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/guest': typeof GuestRouteRouteWithChildren
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/admin/dev-tools': typeof AdminDevToolsRouteRouteWithChildren
  '/guest/$projectId': typeof GuestProjectIdRoute
  '/workspace/$workspaceSlug': typeof WorkspaceWorkspaceSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/guest/': typeof GuestIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/admin/dev-tools/camera': typeof AdminDevToolsCameraRoute
  '/admin/dev-tools/preview-shell': typeof AdminDevToolsPreviewShellRoute
  '/admin/workspaces/create': typeof AdminWorkspacesCreateRoute
  '/workspace/$workspaceSlug/projects': typeof WorkspaceWorkspaceSlugProjectsRoute
  '/workspace/$workspaceSlug/settings': typeof WorkspaceWorkspaceSlugSettingsRoute
  '/admin/workspaces/': typeof AdminWorkspacesIndexRoute
  '/workspace/$workspaceSlug/': typeof WorkspaceWorkspaceSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/guest'
    | '/workspace'
    | '/$'
    | '/login'
    | '/logout'
    | '/admin/dev-tools'
    | '/guest/$projectId'
    | '/workspace/$workspaceSlug'
    | '/admin/'
    | '/guest/'
    | '/workspace/'
    | '/admin/dev-tools/camera'
    | '/admin/dev-tools/preview-shell'
    | '/admin/workspaces/create'
    | '/workspace/$workspaceSlug/projects'
    | '/workspace/$workspaceSlug/settings'
    | '/admin/workspaces'
    | '/workspace/$workspaceSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/logout'
    | '/admin/dev-tools'
    | '/guest/$projectId'
    | '/admin'
    | '/guest'
    | '/workspace'
    | '/admin/dev-tools/camera'
    | '/admin/dev-tools/preview-shell'
    | '/admin/workspaces/create'
    | '/workspace/$workspaceSlug/projects'
    | '/workspace/$workspaceSlug/settings'
    | '/admin/workspaces'
    | '/workspace/$workspaceSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/guest'
    | '/workspace'
    | '/$'
    | '/login'
    | '/logout'
    | '/admin/dev-tools'
    | '/guest/$projectId'
    | '/workspace/$workspaceSlug'
    | '/admin/'
    | '/guest/'
    | '/workspace/'
    | '/admin/dev-tools/camera'
    | '/admin/dev-tools/preview-shell'
    | '/admin/workspaces/create'
    | '/workspace/$workspaceSlug/projects'
    | '/workspace/$workspaceSlug/settings'
    | '/admin/workspaces/'
    | '/workspace/$workspaceSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/guest/': {
      id: '/guest/'
      path: '/'
      fullPath: '/guest/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/workspace/$workspaceSlug': {
      id: '/workspace/$workspaceSlug'
      path: '/$workspaceSlug'
      fullPath: '/workspace/$workspaceSlug'
      preLoaderRoute: typeof WorkspaceWorkspaceSlugRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/guest/$projectId': {
      id: '/guest/$projectId'
      path: '/$projectId'
      fullPath: '/guest/$projectId'
      preLoaderRoute: typeof GuestProjectIdRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/admin/dev-tools': {
      id: '/admin/dev-tools'
      path: '/dev-tools'
      fullPath: '/admin/dev-tools'
      preLoaderRoute: typeof AdminDevToolsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/workspace/$workspaceSlug/': {
      id: '/workspace/$workspaceSlug/'
      path: '/'
      fullPath: '/workspace/$workspaceSlug/'
      preLoaderRoute: typeof WorkspaceWorkspaceSlugIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceSlugRoute
    }
    '/admin/workspaces/': {
      id: '/admin/workspaces/'
      path: '/workspaces'
      fullPath: '/admin/workspaces'
      preLoaderRoute: typeof AdminWorkspacesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/workspace/$workspaceSlug/settings': {
      id: '/workspace/$workspaceSlug/settings'
      path: '/settings'
      fullPath: '/workspace/$workspaceSlug/settings'
      preLoaderRoute: typeof WorkspaceWorkspaceSlugSettingsRouteImport
      parentRoute: typeof WorkspaceWorkspaceSlugRoute
    }
    '/workspace/$workspaceSlug/projects': {
      id: '/workspace/$workspaceSlug/projects'
      path: '/projects'
      fullPath: '/workspace/$workspaceSlug/projects'
      preLoaderRoute: typeof WorkspaceWorkspaceSlugProjectsRouteImport
      parentRoute: typeof WorkspaceWorkspaceSlugRoute
    }
    '/admin/workspaces/create': {
      id: '/admin/workspaces/create'
      path: '/workspaces/create'
      fullPath: '/admin/workspaces/create'
      preLoaderRoute: typeof AdminWorkspacesCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dev-tools/preview-shell': {
      id: '/admin/dev-tools/preview-shell'
      path: '/preview-shell'
      fullPath: '/admin/dev-tools/preview-shell'
      preLoaderRoute: typeof AdminDevToolsPreviewShellRouteImport
      parentRoute: typeof AdminDevToolsRouteRoute
    }
    '/admin/dev-tools/camera': {
      id: '/admin/dev-tools/camera'
      path: '/camera'
      fullPath: '/admin/dev-tools/camera'
      preLoaderRoute: typeof AdminDevToolsCameraRouteImport
      parentRoute: typeof AdminDevToolsRouteRoute
    }
  }
}

interface AdminDevToolsRouteRouteChildren {
  AdminDevToolsCameraRoute: typeof AdminDevToolsCameraRoute
  AdminDevToolsPreviewShellRoute: typeof AdminDevToolsPreviewShellRoute
}

const AdminDevToolsRouteRouteChildren: AdminDevToolsRouteRouteChildren = {
  AdminDevToolsCameraRoute: AdminDevToolsCameraRoute,
  AdminDevToolsPreviewShellRoute: AdminDevToolsPreviewShellRoute,
}

const AdminDevToolsRouteRouteWithChildren =
  AdminDevToolsRouteRoute._addFileChildren(AdminDevToolsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminDevToolsRouteRoute: typeof AdminDevToolsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminWorkspacesCreateRoute: typeof AdminWorkspacesCreateRoute
  AdminWorkspacesIndexRoute: typeof AdminWorkspacesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDevToolsRouteRoute: AdminDevToolsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminWorkspacesCreateRoute: AdminWorkspacesCreateRoute,
  AdminWorkspacesIndexRoute: AdminWorkspacesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestProjectIdRoute: typeof GuestProjectIdRoute
  GuestIndexRoute: typeof GuestIndexRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestProjectIdRoute: GuestProjectIdRoute,
  GuestIndexRoute: GuestIndexRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

interface WorkspaceWorkspaceSlugRouteChildren {
  WorkspaceWorkspaceSlugProjectsRoute: typeof WorkspaceWorkspaceSlugProjectsRoute
  WorkspaceWorkspaceSlugSettingsRoute: typeof WorkspaceWorkspaceSlugSettingsRoute
  WorkspaceWorkspaceSlugIndexRoute: typeof WorkspaceWorkspaceSlugIndexRoute
}

const WorkspaceWorkspaceSlugRouteChildren: WorkspaceWorkspaceSlugRouteChildren =
  {
    WorkspaceWorkspaceSlugProjectsRoute: WorkspaceWorkspaceSlugProjectsRoute,
    WorkspaceWorkspaceSlugSettingsRoute: WorkspaceWorkspaceSlugSettingsRoute,
    WorkspaceWorkspaceSlugIndexRoute: WorkspaceWorkspaceSlugIndexRoute,
  }

const WorkspaceWorkspaceSlugRouteWithChildren =
  WorkspaceWorkspaceSlugRoute._addFileChildren(
    WorkspaceWorkspaceSlugRouteChildren,
  )

interface WorkspaceRouteRouteChildren {
  WorkspaceWorkspaceSlugRoute: typeof WorkspaceWorkspaceSlugRouteWithChildren
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceWorkspaceSlugRoute: WorkspaceWorkspaceSlugRouteWithChildren,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
